import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Header } from "@/components/header";
import { Toaster } from "sonner";
import PostProvider from "@/store/postProvider";

import { AppModal } from "./(marketing)/app-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Socials",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppModal />
        <div className="h-full">{children}</div>
        <Toaster duration={3000} position="bottom-left" />
      </body>
    </html>
  );
}
